language: java
jdk:
  - openjdk8

install: skip
script:
  - ./build test
after_failure:
  - echo "\n=== SUREFIRE REPORTS ===\n"
  - for F in target/surefire-reports/*.txt; do echo $F; cat $F; echo; done
